// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxohysiwchvmyhzdtffq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4b2h5c2l3Y2h2bXloemR0ZmZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODcwMzgsImV4cCI6MjA2NTE2MzAzOH0.4L_VAy_IQmxsIzG0MfzsdUlf-YFW1_yrbuT34ioBmWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);